### ISSUE TITLE
Some More examples

### ISSUE THREAD

**Issue by folkkerz** [naveen521kk/sxcu#32]
Hey bro Can you pls share some more examples like this (I Don't know much about python😅(
import sxcu
connector = sxcu.SXCU()
result = connector.upload_image("foo.png")
print(result["url"])

For subdomain
And If you are on Telegram can you pls share you id

**Comment by naveen521kk** [comment]
You can pass subdomain as a parameter to `SXCU()` constructor.
For example,
```py
import sxcu
connector = sxcu.SXCU(subdomain="https://custom.shx.is")
result = connector.upload_image("foo.png")
print(result["url"])
```

If it's a private subdomain you can pass `upload_token` as a parameter to `SXCU()` constructor.
Or if you want you can specify the provided `.sxcu` file also as a parameter to it.

**Comment by folkkerz** [comment]
Got it bro thanks😅🙏
