### ISSUE TITLE
Implement Logging

### ISSUE THREAD

**Issue by naveen521kk** [naveen521kk/sxcu#4]
Logging is necessary and can be done easily using the default logging module. This would help to debug errors. A new class for logging would do.

**Comment by Martianmellow12** [comment]
Could you assign this to me? Also, do you want information to be logged to the terminal, a file, or both?

**Comment by naveen521kk** [comment]
Thank you fo your contribution.

I have no specific ideas on this. You can do whatever you feel like doing. Also, this isn't a CLI so possibly logging to file or even better giving a users choice by allowing them to use their own logging module would be better. I am assigning you. @Martianmellow12

**Comment by Martianmellow12** [comment]
School's picking up, so I'm not sure I'll have time to work on it. I'll try to work on it, but if you want to un-assign me so others can work on it, I understand.

**Comment by naveen521kk** [comment]
No worries!

**Comment by naveen521kk** [comment]
I am working on this. I would do a basic one but that needs improvement.

**Comment by naveen521kk** [comment]
Done in #14
