### ISSUE TITLE
Passing image content as parameter rather then image file path

### ISSUE THREAD

**Issue by Hexiro** [naveen521kk/sxcu#89]
## Location
as can be seen [here](https://github.com/naveen521kk/sxcu/blob/76ee1f2965113e6ca7a9678df723d95a866b88ed/sxcu/sxcu.py#L105) (and some other places)
```py
with open(file, "rb") as img_file:
    files = {"file": img_file}
    res = request_handler.post(url, files=files, data=data)
```
## The Problem

The wrapper accepts file paths over the file's content itself and then handles reading from that path. This is a problem when a user gets an image dynamically from some algorithm because then they have to write to the disk and supply that file path (not only slow but can cause errors based on permissions and os differences). 

## The Solution
possible solutions include:
* Make the user handle reading from files.
* having two separate parameters, one being path another being file content and expecting exactly one.
* have one parameter, `file_or_path` which is handled differently based on its data type (bytes == file content, string == file path)

I'd be willing to make a PR if you know which solution you'd like to choose. In my opinion, now is a good time to change something like this because the API is already changing a lot due to v1 being deprecated. Let me know what you think :)

**Comment by naveen521kk** [comment]
Method 3 seems like the best one with backwards compatibility. If the passed parameter is `str` or ``Path` it should be opened and if it is `FileLike` then it should just be passed to requests. I don't think accepting raw bytes would be better, instead one can use https://docs.python.org/3/library/io.html#io.BytesIO to create a file like argument.

**Comment by Hexiro** [comment]
Works for me. Should just be able to check if it has a 'read' method, and if not attempt to open the file path. Am I good to open a PR?

**Comment by naveen521kk** [comment]
> Should just be able to check if it has a 'read' method, and if not attempt to open the file path.

Rather than simply checking for `read` method check whether it is a subclass of [`IOBase`](https://docs.python.org/3/library/io.html?highlight=bytesio#io.IOBase).

>  Am I good to open a PR?

You should wait for #88 which I would complete probably by this weekend.

**Comment by Hexiro** [comment]
Sounds like a plan 👍🏼

**Comment by naveen521kk** [comment]
I guess you can start working now :)
